name: CI
on:
  - push
  - pull_request
jobs:
  continuous-integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - run: make unit_test
      - run: make integration_test
      - run: make build
      - run: make package TAG="${{github.ref_name}}"
      - uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ctalec
          password: ${{ secrets.TOKENHUB }}
      - if: startsWith(github.ref, 'refs/tags/')
        run: make release  TAG="${{github.ref_name}}"
      - run: ls dist/